language: python
python: 2.7
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bc tcsh
script:
  # Test the code snippets.
  - ./util/test_all.bash
  # Test that the docs actually build.
  - cd docs/ && make html
